# Generated by Django 2.2.19 on 2022-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='bad_group', max_length=200),
            preserve_default=False,
        ),
    ]
